
package zoologico;

import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author DAVID NARANJO
 */
public class BrowserLogistica extends javax.swing.JFrame 
{
         private AnimalSalvaje salvaje;
         private DefaultTableModel modTabla1;
         private String [] columnas;
         
         private AnimalDomestico domestico;
         private DefaultTableModel modTabla2;
    
        
         
         private AnimalSilvestre silvestre;
         private DefaultTableModel modTabla3;
     
         
         // declaracion de variables estadisticas
          static int CantSalv = 0, AlmSalvD = 0, CantDom = 0, AlmDomD = 0, CantSilv = 0;
          static int AlmSilvD = 0, AlimTotalD = 0,AlimTotalM, codSv = 0,codD = 0, codSi = 0,CantASD = 0,CantADD = 0,CantASID = 0;
         
         
  
    public BrowserLogistica() {
        initComponents();
        this.setLocationRelativeTo(null);
        modTabla1 = new DefaultTableModel();
        columnas = new String[3];
        columnas[0] = "NivelDePeligrosidad";
        columnas[1]= "Codigo";
        columnas[2]= "Nombre";
        modTabla1.setColumnIdentifiers(columnas);
        tblSalvajes.setModel(modTabla1);
        
        modTabla2 = new DefaultTableModel();
        columnas = new String[3];
        columnas[0] = "Especie";
        columnas[1]= "Codigo";
        columnas[2]= "Nombre";
        modTabla2.setColumnIdentifiers(columnas);
        tblDomesticos.setModel(modTabla2);
        
        modTabla3 = new DefaultTableModel();
        columnas = new String[3];
        columnas[0] = "Tipo";
        columnas[1]= "Codigo";
        columnas[2]= "Nombre";
        modTabla3.setColumnIdentifiers(columnas);
        tblSilvestres.setModel(modTabla3);
      
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalvajes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDomesticos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSilvestres = new javax.swing.JTable();
        jbtAgregar = new javax.swing.JButton();
        jbtLimpiar = new javax.swing.JButton();
        jbtSalvajes = new javax.swing.JButton();
        jbtdomesticos = new javax.swing.JButton();
        jbtSilvestres = new javax.swing.JButton();
        jbtEliminarSv = new javax.swing.JButton();
        jbtEliminarD = new javax.swing.JButton();
        jbtEliminarSi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jrbSalvaje = new javax.swing.JRadioButton();
        jrbDomestico = new javax.swing.JRadioButton();
        jrbSilvestre = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jbtRegresar = new javax.swing.JButton();
        jbtInicio = new javax.swing.JButton();
        jbtContable = new javax.swing.JButton();
        jbtEstadistica = new javax.swing.JButton();
        jbtSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEspecie = new javax.swing.JTextField();
        txtAlimento = new javax.swing.JTextField();
        txtNivPel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoologico/logo zoologico.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblSalvajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblSalvajes);

        tblDomesticos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblDomesticos);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel3.setText(" ANIMALES SALVAJES");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel4.setText("ANIMALES DOMESTICOS");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel5.setText("ANIMALES SILVESTRES");

        tblSilvestres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblSilvestres);

        jbtAgregar.setBackground(new java.awt.Color(51, 204, 0));
        jbtAgregar.setFont(new java.awt.Font("Arial", 1, 14));
        jbtAgregar.setText("AGREGAR");
        jbtAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAgregarActionPerformed(evt);
            }
        });

        jbtLimpiar.setBackground(new java.awt.Color(51, 204, 0));
        jbtLimpiar.setFont(new java.awt.Font("Arial", 1, 14));
        jbtLimpiar.setText("LIMPIAR");
        jbtLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLimpiarActionPerformed(evt);
            }
        });

        jbtSalvajes.setBackground(new java.awt.Color(51, 204, 0));
        jbtSalvajes.setFont(new java.awt.Font("Arial", 1, 14));
        jbtSalvajes.setText("LISTAR SALV.");
        jbtSalvajes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtSalvajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvajesActionPerformed(evt);
            }
        });

        jbtdomesticos.setBackground(new java.awt.Color(51, 204, 0));
        jbtdomesticos.setFont(new java.awt.Font("Arial", 1, 14));
        jbtdomesticos.setText("LISTAR DOM.");
        jbtdomesticos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtdomesticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtdomesticosActionPerformed(evt);
            }
        });

        jbtSilvestres.setBackground(new java.awt.Color(51, 204, 0));
        jbtSilvestres.setFont(new java.awt.Font("Arial", 1, 14));
        jbtSilvestres.setText("LISTAR SILV.");
        jbtSilvestres.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtSilvestres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSilvestresActionPerformed(evt);
            }
        });

        jbtEliminarSv.setBackground(new java.awt.Color(51, 204, 0));
        jbtEliminarSv.setFont(new java.awt.Font("Arial", 1, 14));
        jbtEliminarSv.setText("ELIMINAR SV");
        jbtEliminarSv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtEliminarSv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEliminarSvActionPerformed(evt);
            }
        });

        jbtEliminarD.setBackground(new java.awt.Color(51, 204, 0));
        jbtEliminarD.setFont(new java.awt.Font("Arial", 1, 14));
        jbtEliminarD.setText("ELIMINAR DOM");
        jbtEliminarD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtEliminarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEliminarDActionPerformed(evt);
            }
        });

        jbtEliminarSi.setBackground(new java.awt.Color(51, 204, 0));
        jbtEliminarSi.setFont(new java.awt.Font("Arial", 1, 14));
        jbtEliminarSi.setText("ELIMINAR SILV");
        jbtEliminarSi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtEliminarSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEliminarSiActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbtEliminarSv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtSalvajes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbtEliminarD, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtdomesticos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtSilvestres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtEliminarSi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbtLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, 0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbtSalvajes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtSilvestres, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtdomesticos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbtEliminarD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtEliminarSi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtEliminarSv, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jbtLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup2.add(jrbSalvaje);
        jrbSalvaje.setText("SALVAJE");

        buttonGroup2.add(jrbDomestico);
        jrbDomestico.setText("DOMESTICO");

        buttonGroup2.add(jrbSilvestre);
        jrbSilvestre.setText("SILVESTRE");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbDomestico)
                    .addComponent(jrbSilvestre)
                    .addComponent(jrbSalvaje))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbSalvaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbDomestico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbSilvestre)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel6.setText("TIPO DE ANIMAL");

        jbtRegresar.setBackground(new java.awt.Color(102, 204, 0));
        jbtRegresar.setFont(new java.awt.Font("Arial", 1, 14));
        jbtRegresar.setText("REGRESAR");
        jbtRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRegresarActionPerformed(evt);
            }
        });

        jbtInicio.setBackground(new java.awt.Color(102, 204, 0));
        jbtInicio.setFont(new java.awt.Font("Arial", 1, 14));
        jbtInicio.setText("INICIO");
        jbtInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtInicioActionPerformed(evt);
            }
        });

        jbtContable.setBackground(new java.awt.Color(102, 204, 0));
        jbtContable.setFont(new java.awt.Font("Arial", 1, 14));
        jbtContable.setText("CONTABLE");
        jbtContable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtContable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtContableActionPerformed(evt);
            }
        });

        jbtEstadistica.setBackground(new java.awt.Color(102, 204, 0));
        jbtEstadistica.setFont(new java.awt.Font("Arial", 1, 14));
        jbtEstadistica.setText("ESTADISTICA");
        jbtEstadistica.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEstadisticaActionPerformed(evt);
            }
        });

        jbtSalir.setBackground(new java.awt.Color(102, 204, 0));
        jbtSalir.setFont(new java.awt.Font("Arial", 1, 14));
        jbtSalir.setText("SALIR");
        jbtSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel7.setText("NIV. PELIG.");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel8.setText("NOMBRE");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel9.setText("ALIM/DIA/KG");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel10.setText("TIPO");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel11.setText("ESPECIE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(38, 38, 38))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNivPel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jbtRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(49, 49, 49)
                                    .addComponent(jbtContable, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(jbtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22)
                                    .addComponent(jbtEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jbtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(80, 80, 80))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtNivPel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtContable, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbtRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRegresarActionPerformed
       BrowserVentas Planes = new BrowserVentas();
           Planes.setVisible(true);
           this.setVisible(false);
}//GEN-LAST:event_jbtRegresarActionPerformed

private void jbtInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtInicioActionPerformed
       BrowserIngreso Ingreso = new BrowserIngreso();
           Ingreso.setVisible(true);
           this.setVisible(false);       
}//GEN-LAST:event_jbtInicioActionPerformed

private void jbtContableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtContableActionPerformed
       BrowserContable Contable = new BrowserContable();
                 Contable.setVisible(true);
                 this.setVisible(false);
}//GEN-LAST:event_jbtContableActionPerformed

private void jbtEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEstadisticaActionPerformed
        BrowserEstadistica Estadistica = new BrowserEstadistica();
                 Estadistica.setVisible(true);
                 this.setVisible(false);
}//GEN-LAST:event_jbtEstadisticaActionPerformed

private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirActionPerformed
         System.exit(0);
}//GEN-LAST:event_jbtSalirActionPerformed

private void jbtAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAgregarActionPerformed
          String pNivelPeligrosidad="";
          String pTipo = "";
          String pEspecie = "";
          String pNombre="";
          int pCodigo = 0;
          
          
           if (jrbSalvaje.isSelected()) 
    {   
        pNombre = txtNombre.getText();  
        pNivelPeligrosidad = txtNivPel.getText();
        CantSalv++;
        try {
        AlmSalvD = AlmSalvD  + Integer.parseInt(txtAlimento.getText());
            }
        catch (NumberFormatException ex)
        {
            
        }
        AlimTotalD  = AlimTotalD + AlmSalvD ;
        
        
    
        if (("".equals(pNombre))) 
        {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar el nombre del animal", "Datos vacios", WIDTH);}
        
             else 
        {
              if (("".equals(pNivelPeligrosidad)))
              {
                 JOptionPane.showMessageDialog(rootPane, "Debe digitar el nivel de peligrosidad", "Datos vacios", WIDTH);
              }
            
             else 
              {
              if("".equals(txtAlimento.getText()))
       
              {
                JOptionPane.showMessageDialog(rootPane, "Debe digitar la cantidad de alimento en kilos consumido por dia", "Datos vacios", WIDTH);
              }
              else 
              {
                   codSv++;
                   pCodigo = codSv;
                   salvaje = new AnimalSalvaje(pNivelPeligrosidad, pCodigo, pNombre);
                   Zoologico.arAnimalSalvaje.add(salvaje);
              }
                  
              }
        }
                  
     }

          else 
    {
        if (jrbDomestico.isSelected()) 
    {  
        pNombre = txtNombre.getText();  
        pEspecie = txtEspecie.getText();
        CantDom++;
        
        try {
        AlmDomD = AlmDomD  + Integer.parseInt(txtAlimento.getText());
            }
        catch (NumberFormatException ex)
        {
            
        }
          AlimTotalD  = AlimTotalD + AlmDomD ;
        
        
        if (("".equals(pNombre))) 
        {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar el nombre del animal", "Datos vacios", WIDTH);}
        
             else 
         {
              if (("".equals(pEspecie))) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar la especie de animal", "Datos vacios", WIDTH);
         }
            
         else 
         {
              if("".equals(txtAlimento.getText()))
       
              {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar la cantidad de alimento en kilos consumido por dia", "Datos vacios", WIDTH);
         }
              else {
                    codD++;
                    pCodigo = codD;
        
                   domestico = new AnimalDomestico(pEspecie, pCodigo, pNombre);
                   Zoologico.arAnimalDomestico.add(domestico);
              }
                  
              }
      }
                  
    }
        
         else 
        {
           if (jrbSilvestre.isSelected()) 
    {   
        pNombre = txtNombre.getText();  
        pTipo = txtTipo.getText();
        CantSilv++;
        try {
        AlmSilvD = AlmSilvD  + Integer.parseInt(txtAlimento.getText());
            }
        catch (NumberFormatException ex)
        {
            
        }
         AlimTotalD  = AlimTotalD + AlmSilvD ;
        
        if (("".equals(pNombre))) 
        {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar el nombre del animal", "Datos vacios", WIDTH);
        }
        
             else 
         {
              if (("".equals(pTipo)))
              {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar el tipo de animal", "Datos vacios", WIDTH);
              }
            
         else 
         {
              if("".equals(txtAlimento.getText()))
       
              {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar la cantidad de alimento en kilos consumido por dia", "Datos vacios", WIDTH);
         }
              else {
                      codSi++;
                      pCodigo = codSi;
                   silvestre = new AnimalSilvestre(pTipo, pCodigo, pNombre);
                   Zoologico.arAnimalSilvestre.add(silvestre);
              }
                  
              }
      }
        
         modTabla2.getDataVector().removeAllElements();
                   tblSilvestres.updateUI();

              for (int i = 0; i < Zoologico.arAnimalSilvestre.size(); i++) {
              modTabla2.addRow(new Object[]{Zoologico.arAnimalSilvestre.get(i).getTipo(), Zoologico.arAnimalSilvestre.get(i).getCodigo(), Zoologico.arAnimalSilvestre.get(i).getNombre()});
         }
    }
    
        
    }
         
    }
            if(pCodigo!=0)
            {
              JOptionPane.showMessageDialog(rootPane, "el animal se ingreso correctamente", "Datos vacios", WIDTH); 
            } 
            else 
         {
           JOptionPane.showMessageDialog(rootPane, "Debe seleccionar la clase de animal a ingresar", "Datos vacios", WIDTH); 

         
         }        

          
}//GEN-LAST:event_jbtAgregarActionPerformed

private void jbtSalvajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvajesActionPerformed
             modTabla1.getDataVector().removeAllElements();
                   tblSalvajes.updateUI();

              for (int i = 0; i < Zoologico.arAnimalSalvaje.size(); i++) 
              {
              modTabla1.addRow(new Object[]{Zoologico.arAnimalSalvaje.get(i).getNivelPeligrosidad(), Zoologico.arAnimalSalvaje.get(i).getCodigo(), Zoologico.arAnimalSalvaje.get(i).getNombre()});
}//GEN-LAST:event_jbtSalvajesActionPerformed
}
private void jbtSilvestresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSilvestresActionPerformed
               modTabla3.getDataVector().removeAllElements();
                   tblSilvestres.updateUI();

              for (int i = 0; i < Zoologico.arAnimalSilvestre.size(); i++) {
              modTabla3.addRow(new Object[]{Zoologico.arAnimalSilvestre.get(i).getTipo(), Zoologico.arAnimalSilvestre.get(i).getCodigo(), Zoologico.arAnimalSilvestre.get(i).getNombre()});
}//GEN-LAST:event_jbtSilvestresActionPerformed
}
private void jbtdomesticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtdomesticosActionPerformed
             modTabla2.getDataVector().removeAllElements();
                   tblDomesticos.updateUI();

            for (int i = 0; i < Zoologico.arAnimalDomestico.size(); i++) {
            modTabla2.addRow(new Object[]{Zoologico.arAnimalDomestico.get(i).getespecie(), Zoologico.arAnimalDomestico.get(i).getCodigo(), Zoologico.arAnimalDomestico.get(i).getNombre()});
}//GEN-LAST:event_jbtdomesticosActionPerformed
}
private void jbtLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLimpiarActionPerformed
            buttonGroup2.clearSelection();
            modTabla1.getDataVector().removeAllElements();
                tblSalvajes.updateUI(); 
                modTabla2.getDataVector().removeAllElements();
                tblDomesticos.updateUI(); 
                modTabla3.getDataVector().removeAllElements();
                tblSilvestres.updateUI();  
                txtNombre.setText(null);
                txtTipo.setText(null);
                txtEspecie.setText(null);
                txtNivPel.setText(null);
                txtAlimento.setText(null);
                        
}//GEN-LAST:event_jbtLimpiarActionPerformed

private void jbtEliminarSvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEliminarSvActionPerformed
              
                Zoologico.arAnimalSalvaje.remove(tblSalvajes.getSelectedRow());
                Iterator it = Zoologico.arAnimalSalvaje.iterator();
          DefaultTableModel model = (DefaultTableModel) this.tblSalvajes.getModel();
                 for (int i = 0; i < modTabla1.getRowCount(); i++)
                 {
                 modTabla1.removeRow(i);
                 i-=1;
                 }
}//GEN-LAST:event_jbtEliminarSvActionPerformed

private void jbtEliminarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEliminarDActionPerformed
                Zoologico.arAnimalDomestico.remove(tblDomesticos.getSelectedRow());
                Iterator it = Zoologico.arAnimalDomestico.iterator();
                DefaultTableModel model = (DefaultTableModel) this.tblDomesticos.getModel();
                 for (int i = 0; i < modTabla2.getRowCount(); i++) 
                 {
                 modTabla2.removeRow(i);
                 i-=1;
                 }
                 
}//GEN-LAST:event_jbtEliminarDActionPerformed

private void jbtEliminarSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEliminarSiActionPerformed
                Zoologico.arAnimalSilvestre.remove(tblSilvestres.getSelectedRow());
                Iterator it = Zoologico.arAnimalSilvestre.iterator();
                DefaultTableModel model = (DefaultTableModel) this.tblSilvestres.getModel();
                 for (int i = 0; i < modTabla3.getRowCount(); i++) 
                 {
                 modTabla3.removeRow(i);
                 i-=1;
                 }
}//GEN-LAST:event_jbtEliminarSiActionPerformed






    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrowserLogistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrowserLogistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrowserLogistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrowserLogistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new BrowserLogistica().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtAgregar;
    private javax.swing.JButton jbtContable;
    private javax.swing.JButton jbtEliminarD;
    private javax.swing.JButton jbtEliminarSi;
    private javax.swing.JButton jbtEliminarSv;
    private javax.swing.JButton jbtEstadistica;
    private javax.swing.JButton jbtInicio;
    private javax.swing.JButton jbtLimpiar;
    private javax.swing.JButton jbtRegresar;
    private javax.swing.JButton jbtSalir;
    private javax.swing.JButton jbtSalvajes;
    private javax.swing.JButton jbtSilvestres;
    private javax.swing.JButton jbtdomesticos;
    private javax.swing.JRadioButton jrbDomestico;
    private javax.swing.JRadioButton jrbSalvaje;
    private javax.swing.JRadioButton jrbSilvestre;
    private javax.swing.JTable tblDomesticos;
    private javax.swing.JTable tblSalvajes;
    private javax.swing.JTable tblSilvestres;
    private javax.swing.JTextField txtAlimento;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtNivPel;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}

